name: othello-env
channels:
  - plotly
  - nvidia
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - binutils_impl_linux-64=2.38
  - binutils_linux-64=2.38.0
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cryptography=38.0.4
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.2.26
  - cupti=11.8.0
  - expat=2.6.2
  - ffmpeg=4.2.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fsspec=2024.3.1
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - kaleido-core=0.1.0
  - kernel-headers_linux-64=3.10.0
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=13.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=13.2.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.20.3
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.13.1
  - libzlib=1.2.13
  - llvm-openmp=18.1.4
  - lz4-c=1.9.4
  - magma=2.7.1
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.1.0
  - mpfr=4.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.3
  - nspr=4.32
  - nss=3.69
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openssl=3.3.1
  - pip=24.0
  - plotly-orca=1.3.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-kaleido=0.1.0
  - python_abi=3.11
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - tk=8.6.14
  - torchtriton=2.3.0
  - typing_extensions=4.11.0
  - wheel=0.43.0
  - x264=1!157.20191217
  - xvfbwrapper=0.2.9
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - accelerate==0.30.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - ale-py==0.8.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - anyio==4.4.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - automated-interpretability==0.0.5
      - autorom==0.4.2
      - autorom-accept-rom-license==0.6.1
      - babe==0.0.7
      - babel==2.15.0
      - beartype==0.14.1
      - beautifulsoup4==4.12.3
      - better-abc==0.0.3
      - bidict==0.23.1
      - bleach==6.1.0
      - blinker==1.8.2
      - blobfile==2.1.1
      - boostedblob==0.15.4
      - box2d-py==2.3.8
      - cachetools==5.3.3
      - certifi==2024.2.2
      - cffi==1.16.0
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - circuitsvis==0.0.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - cmake==3.29.3
      - comm==0.2.2
      - config2py==0.1.36
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==2.19.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diffusers==0.28.0
      - dill==0.3.8
      - distlib==0.3.8
      - docker-pycreds==0.4.0
      - dol==0.2.62
      - eindex-callum==0.1.1
      - einops==0.8.0
      - etils==1.8.0
      - executing==2.0.1
      - fancy-einsum==0.0.3
      - farama-notifications==0.0.4
      - fastjsonschema==2.19.1
      - filelock==3.14.0
      - fonttools==4.52.4
      - fqdn==1.5.1
      - frozendict==2.4.4
      - frozenlist==1.4.1
      - ftfy==6.2.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - gprof2dot==2024.6.6
      - graze==0.1.24
      - grpcio==1.64.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.29.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.23.2
      - i2==0.1.27
      - identify==2.5.36
      - imageio==2.37.0
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==5.2.0
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - inquirerpy==0.3.4
      - ipykernel==6.29.4
      - ipython==8.24.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.7.1
      - isoduration==20.11.0
      - jaxtyping==0.2.29
      - jedi==0.19.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpickle==3.2.2
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==1.1.1
      - kaleido==0.0.3
      - kiwisolver==1.4.5
      - lit==18.1.6
      - lxml==4.9.4
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.1
      - mistune==3.0.2
      - moviepy==2.1.2
      - mpmath==1.3.0
      - mujoco==3.1.5
      - multidict==6.0.5
      - multiprocess==0.70.16
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - neel-plotly==0.0.0
      - nest-asyncio==1.6.0
      - nltk==3.9.1
      - nnsight==0.0.6
      - nodeenv==1.9.0
      - notebook==7.2.0
      - notebook-shim==0.2.4
      - numpy-stl==3.1.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - openai==0.28.0
      - opencv-python==4.9.0.80
      - orjson==3.10.7
      - overrides==7.7.0
      - packaging==24.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathtools==0.1.2
      - patsy==0.5.6
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==10.3.0
      - platformdirs==4.2.2
      - plotly==5.22.0
      - plotly-express==0.4.1
      - pluggy==1.5.0
      - portalocker==2.8.2
      - pre-commit==3.7.1
      - proglog==0.1.10
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.45
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py2store==0.1.20
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pycparser==2.22
      - pycryptodomex==3.20.0
      - pydantic==2.7.2
      - pydantic-core==2.18.3
      - pydeck==0.9.1
      - pygame==2.5.2
      - pygame-screen-record==0.1.1
      - pygments==2.18.0
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - pytest==8.2.1
      - pytest-profiling==1.7.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-engineio==4.9.1
      - python-graphviz==0.20.3
      - python-json-logger==2.0.7
      - python-socketio==5.11.2
      - python-utils==3.8.2
      - pytz==2024.1
      - pyvis==0.3.2
      - pyzmq==26.0.0
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - referencing==0.35.1
      - regex==2024.5.15
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - sae-lens==3.17.1
      - safetensors==0.4.3
      - scikit-fuzzy==0.4.2
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.3.1
      - setproctitle==1.3.3
      - shapely==2.0.5
      - shellingham==1.5.4
      - shimmy==0.2.1
      - simple-websocket==1.0.0
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - statsmodels==0.14.2
      - streamlit==1.35.0
      - streamlit-antd-components==0.2.5
      - streamlit-image-select==0.6.0
      - streamlit-on-hover-tabs==1.0.1
      - sympy==1.12.1
      - tabulate==0.9.0
      - tenacity==8.3.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tiktoken==0.6.0
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - toolz==0.12.1
      - torchdata==0.6.1
      - torchinfo==1.8.0
      - torchtext==0.15.2
      - torchviz==0.0.2
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformer-lens==2.0.0
      - transformers==4.41.2
      - transformers-stream-generator==0.0.5
      - triton==2.0.0
      - typeguard==2.13.3
      - typer==0.12.4
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==1.26.19
      - uvloop==0.20.0
      - virtualenv==20.26.2
      - wandb==0.13.10
      - watchdog==4.0.1
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - widgetsnbextension==3.6.6
      - wsproto==1.2.0
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.19.0
      - zstandard==0.22.0
